FROM node:20-slim 

# Install necessary languages/tools and build essentials
RUN apt-get update && apt-get install -y \
    python3 \
    ruby \
    default-jdk \
    golang \
    rustc \
    build-essential \
    libsecret-1-0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./

# IMPORTANT: Force a clean npm install with the new Node.js version
RUN npm install

COPY . ./

RUN npm rebuild node-pty

CMD ["node", "index.js"]